name: Movie Poster every 5h (no duplicates this month)

on:
  schedule:
    - cron: "0 */5 * * *"      # every 5 hours
  workflow_dispatch:

env:
  TZ: UTC                       # keep everything UTC to avoid DST quirks

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run poster bot
        run: python main.py
        env:
          TMDB_API_KEY:              ${{ secrets.TMDB_API_KEY }}
          CLOUDINARY_CLOUD_NAME:     ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY:        ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET:     ${{ secrets.CLOUDINARY_API_SECRET }}
          FACEBOOK_PAGE_ACCESS_TOKEN: ${{ secrets.FACEBOOK_PAGE_ACCESS_TOKEN }}
          FACEBOOK_PAGE_ID:          ${{ secrets.FACEBOOK_PAGE_ID }}
          GEMINI_API_KEY:            ${{ secrets.GEMINI_API_KEY }}
